# Generated by Django 4.0.1 on 2022-02-12 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_remove_cashflow_account_event_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ISIN', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityTrade',
            fields=[
                ('accountingevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolioapp.accountingevent')),
                ('security_amount', models.FloatField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.security')),
            ],
            bases=('portfolioapp.accountingevent',),
        ),
    ]
