# Generated by Django 4.0.1 on 2022-02-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_security_securitytrade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='security',
            options={'verbose_name_plural': 'securities'},
        ),
        migrations.AddField(
            model_name='security',
            name='full_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securitytrade',
            name='fee',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securitytrade',
            name='tax',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
