# Generated by Django 4.0.1 on 2022-02-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_alter_security_options_security_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='full_name',
        ),
    ]
