# Generated by Django 4.0.1 on 2022-02-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_remove_security_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentaccount',
            name='latest_event_rank',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='security',
            name='ISIN',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
