# Generated by Django 4.0.1 on 2022-02-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0006_investmentaccount_latest_event_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentaccount',
            name='latest_event_rank',
        ),
    ]
