# Generated by Django 4.0.1 on 2022-02-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0007_remove_investmentaccount_latest_event_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('price', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.currency')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.security')),
            ],
        ),
    ]
