# Generated by Django 3.2.12 on 2022-02-17 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0008_securityquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.currency')),
            ],
        ),
        migrations.AddField(
            model_name='security',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.country'),
        ),
    ]
