# Generated by Django 3.2.12 on 2022-02-17 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0009_auto_20220217_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.RemoveField(
            model_name='security',
            name='country',
        ),
    ]
