# Generated by Django 3.2.12 on 2022-02-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0012_security_yahoo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('last_quote_refresh', models.DateTimeField()),
            ],
        ),
    ]
