# Generated by Django 3.2.12 on 2022-02-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0013_queuemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuemanager',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queuemanager',
            name='period',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
