# Generated by Django 3.2.12 on 2022-02-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0014_auto_20220219_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QueueManager',
            new_name='QuoteManager',
        ),
    ]
