# Generated by Django 3.2.12 on 2022-03-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0015_rename_queuemanager_quotemanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=51),
        ),
    ]
